id: kterm
name: KTerm
author: bfabiszewski
description: "Terminal emulator for Kindle. Required by many other packages."
artifacts:
  - platform: kindlepw2
    source:
      type: github_release
      repo: bfabiszewski/kterm
      tag: "v2.6"
      asset_pattern: "kterm-kindle-*.zip"
      asset_exclude_pattern: "*-armhf*"
      extract_subdir: kterm
  - platform: kindlehf
    source:
      type: github_release
      repo: bfabiszewski/kterm
      tag: "v2.6"
      asset_pattern: "kterm-kindle-*-armhf.zip"
      extract_subdir: kterm
