id: koreader
name: KOReader
author: KOReader Team
description: "An ebook reader application supporting PDF, DjVu, EPUB, FB2 and many more formats"
artifacts:
  - platform: kindlepw2
    source:
      type: github_release
      repo: koreader/koreader
      tag: "v2026.07.1"
      asset_pattern: "koreader-kindlepw2-*.zip"
      extract_subdir: koreader
  - platform: kindlehf
    source:
      type: github_release
      repo: koreader/koreader
      tag: "v2026.07.1"
      asset_pattern: "koreader-kindlehf-*.zip"
      extract_subdir: koreader
